In [28]:
import pandas as pd

df = pd.read_csv("../data/raw/procurement_kpi_dataset.csv")

df.head()

,PO_ID,Supplier,Order_Date,Delivery_Date,Item_Category,Order_Status,Quantity,Unit_Price,Negotiated_Price,Defective_Units,Compliance
0,PO-00001,Alpha_Inc,2023-10-17,2023-10-25,Office Supplies,Cancelled,1176,20.13,17.81,NaN,Yes
1,PO-00002,Delta_Logistics,2022-04-25,2022-05-05,Office Supplies,Delivered,1509,39.32,37.34,235.0,Yes
2,PO-00003,Gamma_Co,2022-01-26,2022-02-15,MRO,Delivered,910,95.51,92.26,41.0,Yes
3,PO-00004,Beta_Supplies,2022-10-09,2022-10-28,Packaging,Delivered,1344,99.85,95.52,112.0,Yes
4,PO-00005,Delta_Logistics,2022-09-08,2022-09-20,Raw Materials,Delivered,1180,64.07,60.53,171.0,No

In [29]:
df.shape

(777, 11)

In [30]:
df.columns

Index(['PO_ID', 'Supplier', 'Order_Date', 'Delivery_Date', 'Item_Category',
       'Order_Status', 'Quantity', 'Unit_Price', 'Negotiated_Price',
       'Defective_Units', 'Compliance'],
      dtype='str')

In [31]:
df.info

<bound method DataFrame.info of         PO_ID         Supplier  Order_Date Delivery_Date    Item_Category  \
0    PO-00001        Alpha_Inc  2023-10-17    2023-10-25  Office Supplies
1    PO-00002  Delta_Logistics  2022-04-25    2022-05-05  Office Supplies
2    PO-00003         Gamma_Co  2022-01-26    2022-02-15              MRO
3    PO-00004    Beta_Supplies  2022-10-09    2022-10-28        Packaging
4    PO-00005  Delta_Logistics  2022-09-08    2022-09-20    Raw Materials
..        ...              ...         ...           ...              ...
772  PO-00773  Delta_Logistics  2023-02-11    2023-02-20      Electronics
773  PO-00774        Alpha_Inc  2022-07-23           NaN  Office Supplies
774  PO-00775         Gamma_Co  2022-03-19    2022-04-07    Raw Materials
775  PO-00776    Beta_Supplies  2023-08-30    2023-09-11              MRO
776  PO-00777    Beta_Supplies  2023-12-09    2023-12-11  Office Supplies

    Order_Status  Quantity  Unit_Price  Negotiated_Price  Defective_Units  \
0      Cancelled      1176       20.13             17.81              NaN
1      Delivered      1509       39.32             37.34            235.0
2      Delivered       910       95.51             92.26             41.0
3      Delivered      1344       99.85             95.52            112.0
4      Delivered      1180       64.07             60.53            171.0
..           ...       ...         ...               ...              ...
772    Delivered      1685       43.42             42.24            262.0
773    Delivered       445       68.94             60.35              7.0
774    Delivered       494       94.82             81.89             29.0
775    Delivered      1306       21.05             18.27            128.0
776    Delivered      1988      105.20             93.23            187.0

    Compliance
0          Yes
1          Yes
2          Yes
3          Yes
4           No
..         ...
772        Yes
773        Yes
774        Yes
775        Yes
776        Yes

[777 rows x 11 columns]>

In [32]:
df.describe(include="all")

,PO_ID,Supplier,Order_Date,Delivery_Date,Item_Category,Order_Status,Quantity,Unit_Price,Negotiated_Price,Defective_Units,Compliance
count,777,777,777,690,777,777,777.000000,777.000000,777.000000,641.000000,777
unique,777,5,476,449,5,4,NaN,NaN,NaN,NaN,2
top,PO-00001,Delta_Logistics,2022-09-29,2023-03-26,Office Supplies,Delivered,NaN,NaN,NaN,NaN,Yes
freq,1,171,6,4,174,560,NaN,NaN,NaN,NaN,640
mean,NaN,NaN,NaN,NaN,NaN,NaN,1094.660232,58.283822,53.660721,74.803432,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,647.844551,28.101315,26.094930,69.187870,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,51.000000,10.840000,9.270000,0.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,615.000000,33.290000,30.460000,26.000000,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,1075.000000,58.950000,53.800000,49.000000,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,1548.000000,83.130000,76.550000,100.000000,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,5000.000000,109.170000,107.390000,321.000000,NaN

In [33]:
df.isna().sum()

PO_ID                 0
Supplier              0
Order_Date            0
Delivery_Date        87
Item_Category         0
Order_Status          0
Quantity              0
Unit_Price            0
Negotiated_Price      0
Defective_Units     136
Compliance            0
dtype: int64

In [34]:
df.duplicated().sum()

np.int64(0)

In [35]:
%pip install openpyxl

Requirement already satisfied: openpyxl in C:\Users\Matin\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in C:\Users\Matin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [36]:
quality_report = pd.DataFrame({
    "column": df.columns,
    "data_type": df.dtypes.astype(str).values,
    "missing_values": df.isna().sum().values,
    "missing_percentage": (df.isna().sum().values / len(df) *100).round(2),
    "unique_values": df.nunique().values
})
quality_report.to_excel("../data/validation/data_quality_report.xlsx", index=False)

quality_report

,column,data_type,missing_values,missing_percentage,unique_values
0,PO_ID,str,0,0.0,777
1,Supplier,str,0,0.0,5
2,Order_Date,str,0,0.0,476
3,Delivery_Date,str,87,11.2,449
4,Item_Category,str,0,0.0,5
5,Order_Status,str,0,0.0,4
6,Quantity,int64,0,0.0,623
7,Unit_Price,float64,0,0.0,747
8,Negotiated_Price,float64,0,0.0,752
9,Defective_Units,float64,136,17.5,202
10,Compliance,str,0,0.0,2

In [37]:
df_clean = df.copy()

In [38]:
df_clean.columns = (
    df_clean.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("-", "_")
    .str.replace("/", "_")
)
df_clean.columns

Index(['po_id', 'supplier', 'order_date', 'delivery_date', 'item_category',
       'order_status', 'quantity', 'unit_price', 'negotiated_price',
       'defective_units', 'compliance'],
      dtype='str')

In [39]:
text_cols = df_clean.select_dtypes(include="object").columns

for col in text_cols: 
        df_clean[col] = df_clean[col].astype(str).str.strip()

C:\Users\Matin\AppData\Local\Temp\ipykernel_30636\796316355.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_cols = df_clean.select_dtypes(include="object").columns

In [40]:
duplicates_before = df_clean.duplicated().sum()
print("Duplikate vorher:", duplicates_before)

df_clean = df_clean.drop_duplicates()

duplicates_after = df_clean.duplicated().sum()
print("Dublikate nachher:", duplicates_after)

Duplikate vorher: 0
Dublikate nachher: 0

In [41]:
df_clean.head()

,po_id,supplier,order_date,delivery_date,item_category,order_status,quantity,unit_price,negotiated_price,defective_units,compliance
0,PO-00001,Alpha_Inc,2023-10-17,2023-10-25,Office Supplies,Cancelled,1176,20.13,17.81,NaN,Yes
1,PO-00002,Delta_Logistics,2022-04-25,2022-05-05,Office Supplies,Delivered,1509,39.32,37.34,235.0,Yes
2,PO-00003,Gamma_Co,2022-01-26,2022-02-15,MRO,Delivered,910,95.51,92.26,41.0,Yes
3,PO-00004,Beta_Supplies,2022-10-09,2022-10-28,Packaging,Delivered,1344,99.85,95.52,112.0,Yes
4,PO-00005,Delta_Logistics,2022-09-08,2022-09-20,Raw Materials,Delivered,1180,64.07,60.53,171.0,No

In [42]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 777 entries, 0 to 776
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   po_id             777 non-null    str
 1   supplier          777 non-null    str
 2   order_date        777 non-null    str
 3   delivery_date     690 non-null    str
 4   item_category     777 non-null    str
 5   order_status      777 non-null    str
 6   quantity          777 non-null    int64
 7   unit_price        777 non-null    float64
 8   negotiated_price  777 non-null    float64
 9   defective_units   641 non-null    float64
 10  compliance        777 non-null    str
dtypes: float64(3), int64(1), str(7)
memory usage: 66.9 KB

In [43]:
df_clean.isna().sum()

po_id                 0
supplier              0
order_date            0
delivery_date        87
item_category         0
order_status          0
quantity              0
unit_price            0
negotiated_price      0
defective_units     136
compliance            0
dtype: int64

In [44]:
df_clean.columns

Index(['po_id', 'supplier', 'order_date', 'delivery_date', 'item_category',
       'order_status', 'quantity', 'unit_price', 'negotiated_price',
       'defective_units', 'compliance'],
      dtype='str')

In [45]:
df_clean["order_status"].unique()

<StringArray>
['Cancelled', 'Delivered', 'Partially Delivered', 'Pending']
Length: 4, dtype: str

In [46]:
df_clean["compliance"].unique()

<StringArray>
['Yes', 'No']
Length: 2, dtype: str

In [47]:
df_clean["item_category"].unique()

<StringArray>
['Office Supplies', 'MRO', 'Packaging', 'Raw Materials', 'Electronics']
Length: 5, dtype: str

In [48]:
df_clean["supplier"].unique()

<StringArray>
['Alpha_Inc', 'Delta_Logistics', 'Gamma_Co', 'Beta_Supplies', 'Epsilon_Group']
Length: 5, dtype: str

In [49]:
df_clean["order_date"] = pd.to_datetime(df_clean["order_date"], errors="coerce")
df_clean["delivery_date"] = pd.to_datetime(df_clean["delivery_date"], errors="coerce")

numeric_cols = ["quantity", "unit_price", "negotiated_price", "defective_units"]

for col in numeric_cols:
    df_clean[col] = pd.to_numeric(df_clean[col], errors="coerce")

In [50]:
df_clean["order_year"] = df_clean["order_date"].dt.year
df_clean["order_month"] = df_clean["order_date"].dt.month
df_clean["year_month"] = df_clean["order_date"].dt.to_period("M").astype(str)

df_clean["lead_time_days"] = (df_clean["delivery_date"] - df_clean["order_date"]).dt.days

df_clean["original_spend"] = df_clean["quantity"] * df_clean["unit_price"]
df_clean["negotiated_spend"] = df_clean["quantity"] * df_clean["negotiated_price"]

df_clean["savings"] = df_clean["original_spend"] - df_clean["negotiated_spend"]

df_clean["savings_rate"] = df_clean["savings"] / df_clean["original_spend"]

df_clean["defect_rate"] = df_clean["defective_units"] / df_clean["quantity"]

In [51]:
df_clean.columns

Index(['po_id', 'supplier', 'order_date', 'delivery_date', 'item_category',
       'order_status', 'quantity', 'unit_price', 'negotiated_price',
       'defective_units', 'compliance', 'order_year', 'order_month',
       'year_month', 'lead_time_days', 'original_spend', 'negotiated_spend',
       'savings', 'savings_rate', 'defect_rate'],
      dtype='str')

In [52]:
df_clean[
    [
        "po_id",
        "supplier",
        "order_date",
        "delivery_date",
        "lead_time_days",
        "quantity",
        "unit_price",
        "negotiated_price",
        "original_spend",
        "negotiated_spend",
        "savings",
        "savings_rate",
        "defect_rate"
    ]
].head()

,po_id,supplier,order_date,delivery_date,lead_time_days,quantity,unit_price,negotiated_price,original_spend,negotiated_spend,savings,savings_rate,defect_rate
0,PO-00001,Alpha_Inc,2023-10-17,2023-10-25,8.0,1176,20.13,17.81,23672.88,20944.56,2728.32,0.115251,NaN
1,PO-00002,Delta_Logistics,2022-04-25,2022-05-05,10.0,1509,39.32,37.34,59333.88,56346.06,2987.82,0.050356,0.155732
2,PO-00003,Gamma_Co,2022-01-26,2022-02-15,20.0,910,95.51,92.26,86914.10,83956.60,2957.50,0.034028,0.045055
3,PO-00004,Beta_Supplies,2022-10-09,2022-10-28,19.0,1344,99.85,95.52,134198.40,128378.88,5819.52,0.043365,0.083333
4,PO-00005,Delta_Logistics,2022-09-08,2022-09-20,12.0,1180,64.07,60.53,75602.60,71425.40,4177.20,0.055252,0.144915

In [53]:

df_clean[df_clean["lead_time_days"] < 0]

,po_id,supplier,order_date,delivery_date,item_category,order_status,quantity,unit_price,negotiated_price,defective_units,compliance,order_year,order_month,year_month,lead_time_days,original_spend,negotiated_spend,savings,savings_rate,defect_rate
100,PO-00101,Alpha_Inc,2022-02-27,2022-02-22,Office Supplies,Delivered,211,75.69,65.4,2.0,Yes,2022,2,2022-02,-5.0,15970.59,13799.4,2171.19,0.135949,0.009479

In [54]:
df_clean[["original_spend", "negotiated_spend", "savings", "defect_rate", "lead_time_days"]].describe()

,original_spend,negotiated_spend,savings,defect_rate,lead_time_days
count,777.000000,777.000000,777.000000,641.000000,690.000000
mean,63455.370476,58396.005650,5059.364826,0.070063,10.776812
std,52292.141676,48236.432418,5465.204601,0.050069,5.729210
min,865.900000,772.800000,43.020000,0.000000,-5.000000
25%,24614.400000,22221.850000,1423.520000,0.027835,6.000000
50%,50426.250000,46776.360000,3117.500000,0.051515,11.000000
75%,89803.970000,83088.710000,6713.500000,0.105169,16.000000
max,444800.000000,432900.000000,59400.000000,0.357143,20.000000

In [55]:
df_clean["order_status"].unique()

<StringArray>
['Cancelled', 'Delivered', 'Partially Delivered', 'Pending']
Length: 4, dtype: str

In [56]:
df_clean["compliance"].unique()

<StringArray>
['Yes', 'No']
Length: 2, dtype: str

In [57]:
df_clean["is_delivered"] = (df_clean["order_status"] == "Delivered").astype(int)
df_clean["is_partially_delivered"] = (df_clean["order_status"] == "Partially Delivered").astype(int)
df_clean["is_pending"] = (df_clean["order_status"] == "Pending").astype(int)
df_clean["is_cancelled"] = (df_clean["order_status"] == "Cancelled").astype(int)

df_clean["is_completed_delivery"] = (
    df_clean["order_status"].isin(["Delivered", "Partially Delivered"])
).astype(int)

df_clean["is_compliant"] = (df_clean["compliance"] == "Yes").astype(int)

In [58]:
df_clean[
    [
        "po_id",
        "supplier",
        "order_status",
        "compliance",
        "quantity",
        "unit_price",
        "negotiated_price",
        "original_spend",
        "negotiated_spend",
        "savings",
        "savings_rate",
        "defective_units",
        "defect_rate",
        "lead_time_days",
        "is_completed_delivery",
        "is_compliant"
    ]
].head()

,po_id,supplier,order_status,compliance,quantity,unit_price,negotiated_price,original_spend,negotiated_spend,savings,savings_rate,defective_units,defect_rate,lead_time_days,is_completed_delivery,is_compliant
0,PO-00001,Alpha_Inc,Cancelled,Yes,1176,20.13,17.81,23672.88,20944.56,2728.32,0.115251,NaN,NaN,8.0,0,1
1,PO-00002,Delta_Logistics,Delivered,Yes,1509,39.32,37.34,59333.88,56346.06,2987.82,0.050356,235.0,0.155732,10.0,1,1
2,PO-00003,Gamma_Co,Delivered,Yes,910,95.51,92.26,86914.10,83956.60,2957.50,0.034028,41.0,0.045055,20.0,1,1
3,PO-00004,Beta_Supplies,Delivered,Yes,1344,99.85,95.52,134198.40,128378.88,5819.52,0.043365,112.0,0.083333,19.0,1,1
4,PO-00005,Delta_Logistics,Delivered,No,1180,64.07,60.53,75602.60,71425.40,4177.20,0.055252,171.0,0.144915,12.0,1,0

In [59]:
df_clean.to_csv("../data/cleaned/procurement_cleaned.csv", index=False)

In [60]:
df_clean.to_excel("../data/validation/excel_validation.xlsx", index=False)

PermissionError: [Errno 13] Permission denied: '../data/validation/excel_validation.xlsx'

In [61]:
df_clean.to_excel("../data/cleaned/procurement_cleaned.xlsx", index=False)